worker_processes  1;

events {
    worker_connections  1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            # Call script when the stream is published
            exec_publish /etc/nginx/scripts/publish.sh $name;
        }
    }
}