FROM golang:1.26 as builder

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /vod-service cmd/vod-service/main.go

FROM alpine:3.24

RUN apk add ffmpeg
COPY --from=builder /vod-service /vod-service

EXPOSE 8080

CMD ["/vod-service"]