version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/TUM-Dev/gocast

# For a description for each linter, see https://golangci-lint.run/usage/linters/.
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - dupl
    - gocyclo
    - gocritic
    - bidichk
    - ineffassign
    - revive
    - nakedret
    - unconvert
    - wastedassign
    - nolintlint
  default: none

  settings:
    staticcheck:
      checks: [ "all", "-ST1000", "-ST1003", "-ST1005", "-QF1008", "-QF1001", "-SA1019" ]
    nakedret:
      max-func-lines: 0
    gocyclo:
      min-complexity: 40 # todo: refactor (r mainRoutes) WatchPage and then remove
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        #- name: exported todo: revisit.
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: duplicated-imports
        - name: modifies-value-receiver
  exclusions:
    paths:
      - node_modules
      - template
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gofumpt
          - dupl
          - gosec
          - unparam
          - staticcheck


run:
  go: '1.24'
  timeout: 10m
#  skip-dirs:
#    - node_modules
#    - template
