repos:
  - repo: git://github.com/Bahjat/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-static-check # install https://staticcheck.io/docs/
      - id: gofumpt # requires github.com/mvdan/gofumpt
