version: "3.8"

services:
  backend:
    container_name: backend_container
    depends_on:
      - db
    build: .
    ports:
      - 8081:8081
    networks:
      backend-network:
    volumes:
      - ./config.yaml:/etc/TUM-Live/config.yaml
      - type: volume
        source: recordings
        target: /recordings
    restart: always

  db:
    container_name: mariadb_container
    image: mariadb
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      TZ: Europe/Berlin
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
      - mariadb-data:/var/lib/mysql
    networks:
      backend-network:
    ports:
      - 3306:3306
    restart: always

networks:
  backend-network:
    driver: bridge

volumes:
  recordings:
  mariadb-data: