global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gocast-runner"
    static_configs:
      - targets: ["runner:9947"]

  - job_name: "gocast-edge"
    static_configs:
      - targets: ["edge:2112"]