FROM bluenviron/mediamtx:1.21.0 AS mediamtx

FROM alpine:3.24
ADD entrypoint.sh /entrypoint.sh
ADD mediamtx.yml /mediamtx.yml
RUN chmod +x /entrypoint.sh
RUN sed -i 's|authHTTPAddress: https://tum.live/api/selfstream/onPublish|authHTTPAddress: http://tum-live:8081/api/selfstream/onPublish|' /mediamtx.yml

RUN apk add --no-cache \
  ffmpeg \
  tzdata

COPY --from=mediamtx /mediamtx /mediamtx
RUN chmod +x /mediamtx

CMD ["/entrypoint.sh"]
