// Code generated by MockGen. DO NOT EDIT.
// Source: dao/camera-preset.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/joschahenningsen/TUM-Live/model"
)

// MockCameraPresetDao is a mock of CameraPresetDao interface.
type MockCameraPresetDao struct {
	ctrl     *gomock.Controller
	recorder *MockCameraPresetDaoMockRecorder
}

// MockCameraPresetDaoMockRecorder is the mock recorder for MockCameraPresetDao.
type MockCameraPresetDaoMockRecorder struct {
	mock *MockCameraPresetDao
}

// NewMockCameraPresetDao creates a new mock instance.
func NewMockCameraPresetDao(ctrl *gomock.Controller) *MockCameraPresetDao {
	mock := &MockCameraPresetDao{ctrl: ctrl}
	mock.recorder = &MockCameraPresetDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCameraPresetDao) EXPECT() *MockCameraPresetDaoMockRecorder {
	return m.recorder
}

// GetDefaultCameraPreset mocks base method.
func (m *MockCameraPresetDao) GetDefaultCameraPreset(lectureHallID uint) (model.CameraPreset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultCameraPreset", lectureHallID)
	ret0, _ := ret[0].(model.CameraPreset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultCameraPreset indicates an expected call of GetDefaultCameraPreset.
func (mr *MockCameraPresetDaoMockRecorder) GetDefaultCameraPreset(lectureHallID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultCameraPreset", reflect.TypeOf((*MockCameraPresetDao)(nil).GetDefaultCameraPreset), lectureHallID)
}
