// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/joschahenningsen/TUM-Live/model"
)

// MockFileDao is a mock of FileDao interface.
type MockFileDao struct {
	ctrl     *gomock.Controller
	recorder *MockFileDaoMockRecorder
}

// MockFileDaoMockRecorder is the mock recorder for MockFileDao.
type MockFileDaoMockRecorder struct {
	mock *MockFileDao
}

// NewMockFileDao creates a new mock instance.
func NewMockFileDao(ctrl *gomock.Controller) *MockFileDao {
	mock := &MockFileDao{ctrl: ctrl}
	mock.recorder = &MockFileDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileDao) EXPECT() *MockFileDaoMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileDao) DeleteFile(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileDaoMockRecorder) DeleteFile(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileDao)(nil).DeleteFile), ctx, id)
}

// GetFileById mocks base method.
func (m *MockFileDao) GetFileById(ctx context.Context, id string) (model.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileById", ctx, id)
	ret0, _ := ret[0].(model.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileById indicates an expected call of GetFileById.
func (mr *MockFileDaoMockRecorder) GetFileById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileById", reflect.TypeOf((*MockFileDao)(nil).GetFileById), ctx, id)
}

// NewFile mocks base method.
func (m *MockFileDao) NewFile(ctx context.Context, f *model.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFile", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewFile indicates an expected call of NewFile.
func (mr *MockFileDaoMockRecorder) NewFile(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFile", reflect.TypeOf((*MockFileDao)(nil).NewFile), ctx, f)
}

// UpdateFile mocks base method.
func (m *MockFileDao) UpdateFile(ctx context.Context, id string, f *model.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFile", ctx, id, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFile indicates an expected call of UpdateFile.
func (mr *MockFileDaoMockRecorder) UpdateFile(ctx, id, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFile", reflect.TypeOf((*MockFileDao)(nil).UpdateFile), ctx, id, f)
}
