// Code generated by MockGen. DO NOT EDIT.
// Source: job.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	context "context"
	reflect "reflect"

	model "github.com/TUM-Dev/gocast/model"
	gomock "github.com/golang/mock/gomock"
)

// MockJobDao is a mock of JobDao interface.
type MockJobDao struct {
	ctrl     *gomock.Controller
	recorder *MockJobDaoMockRecorder
}

// MockJobDaoMockRecorder is the mock recorder for MockJobDao.
type MockJobDaoMockRecorder struct {
	mock *MockJobDao
}

// NewMockJobDao creates a new mock instance.
func NewMockJobDao(ctrl *gomock.Controller) *MockJobDao {
	mock := &MockJobDao{ctrl: ctrl}
	mock.recorder = &MockJobDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobDao) EXPECT() *MockJobDaoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobDao) Create(arg0 context.Context, arg1 *model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobDaoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobDao)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockJobDao) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJobDaoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJobDao)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockJobDao) Get(arg0 context.Context, arg1 uint) (model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobDaoMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobDao)(nil).Get), arg0, arg1)
}
