// Code generated by MockGen. DO NOT EDIT.
// Source: dao/video-section.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/joschahenningsen/TUM-Live/model"
)

// MockVideoSectionDao is a mock of VideoSectionDao interface.
type MockVideoSectionDao struct {
	ctrl     *gomock.Controller
	recorder *MockVideoSectionDaoMockRecorder
}

// MockVideoSectionDaoMockRecorder is the mock recorder for MockVideoSectionDao.
type MockVideoSectionDaoMockRecorder struct {
	mock *MockVideoSectionDao
}

// NewMockVideoSectionDao creates a new mock instance.
func NewMockVideoSectionDao(ctrl *gomock.Controller) *MockVideoSectionDao {
	mock := &MockVideoSectionDao{ctrl: ctrl}
	mock.recorder = &MockVideoSectionDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoSectionDao) EXPECT() *MockVideoSectionDaoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVideoSectionDao) Create(sections []model.VideoSection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", sections)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVideoSectionDaoMockRecorder) Create(sections interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoSectionDao)(nil).Create), sections)
}

// Delete mocks base method.
func (m *MockVideoSectionDao) Delete(videoSectionID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", videoSectionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoSectionDaoMockRecorder) Delete(videoSectionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoSectionDao)(nil).Delete), videoSectionID)
}

// GetByStreamId mocks base method.
func (m *MockVideoSectionDao) GetByStreamId(streamID uint) ([]model.VideoSection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStreamId", streamID)
	ret0, _ := ret[0].([]model.VideoSection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStreamId indicates an expected call of GetByStreamId.
func (mr *MockVideoSectionDaoMockRecorder) GetByStreamId(streamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStreamId", reflect.TypeOf((*MockVideoSectionDao)(nil).GetByStreamId), streamID)
}

// Update mocks base method.
func (m *MockVideoSectionDao) Update(section *model.VideoSection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", section)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVideoSectionDaoMockRecorder) Update(section interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVideoSectionDao)(nil).Update), section)
}
