// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: notifications.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatus represents the status of a job
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_CREATED     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_CREATED",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_CREATED":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELLED":   5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_notifications_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

// ActionType represents the type of action being executed
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_STREAM      ActionType = 1
	ActionType_ACTION_TYPE_STREAM_END  ActionType = 2
	ActionType_ACTION_TYPE_MK_VOD      ActionType = 3
	ActionType_ACTION_TYPE_CHECK_VOD   ActionType = 4
	ActionType_ACTION_TYPE_MK_THUMB    ActionType = 5
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_STREAM",
		2: "ACTION_TYPE_STREAM_END",
		3: "ACTION_TYPE_MK_VOD",
		4: "ACTION_TYPE_CHECK_VOD",
		5: "ACTION_TYPE_MK_THUMB",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_STREAM":      1,
		"ACTION_TYPE_STREAM_END":  2,
		"ACTION_TYPE_MK_VOD":      3,
		"ACTION_TYPE_CHECK_VOD":   4,
		"ACTION_TYPE_MK_THUMB":    5,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_notifications_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Notification_StreamStart
	//	*Notification_StreamEnd
	//	*Notification_Heartbeat
	//	*Notification_VodReady
	//	*Notification_ThumbnailReady
	//	*Notification_JobUpdate
	Data          isNotification_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetData() isNotification_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetStreamStart() *StreamStartNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_StreamStart); ok {
			return x.StreamStart
		}
	}
	return nil
}

func (x *Notification) GetStreamEnd() *StreamEndNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_StreamEnd); ok {
			return x.StreamEnd
		}
	}
	return nil
}

func (x *Notification) GetHeartbeat() *HeartbeatNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Notification) GetVodReady() *VODReadyNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_VodReady); ok {
			return x.VodReady
		}
	}
	return nil
}

func (x *Notification) GetThumbnailReady() *ThumbnailReadyNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_ThumbnailReady); ok {
			return x.ThumbnailReady
		}
	}
	return nil
}

func (x *Notification) GetJobUpdate() *JobUpdateNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_JobUpdate); ok {
			return x.JobUpdate
		}
	}
	return nil
}

type isNotification_Data interface {
	isNotification_Data()
}

type Notification_StreamStart struct {
	StreamStart *StreamStartNotification `protobuf:"bytes,1,opt,name=stream_start,json=streamStart,oneof"`
}

type Notification_StreamEnd struct {
	StreamEnd *StreamEndNotification `protobuf:"bytes,2,opt,name=stream_end,json=streamEnd,oneof"`
}

type Notification_Heartbeat struct {
	Heartbeat *HeartbeatNotification `protobuf:"bytes,3,opt,name=heartbeat,oneof"`
}

type Notification_VodReady struct {
	VodReady *VODReadyNotification `protobuf:"bytes,4,opt,name=vod_ready,json=vodReady,oneof"`
}

type Notification_ThumbnailReady struct {
	ThumbnailReady *ThumbnailReadyNotification `protobuf:"bytes,5,opt,name=thumbnail_ready,json=thumbnailReady,oneof"`
}

type Notification_JobUpdate struct {
	JobUpdate *JobUpdateNotification `protobuf:"bytes,6,opt,name=job_update,json=jobUpdate,oneof"`
}

func (*Notification_StreamStart) isNotification_Data() {}

func (*Notification_StreamEnd) isNotification_Data() {}

func (*Notification_Heartbeat) isNotification_Data() {}

func (*Notification_VodReady) isNotification_Data() {}

func (*Notification_ThumbnailReady) isNotification_Data() {}

func (*Notification_JobUpdate) isNotification_Data() {}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *StreamInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type StreamStartNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	Url           *string                `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	StreamVersion *StreamVersion         `protobuf:"varint,3,opt,name=stream_version,json=streamVersion,enum=protobuf.StreamVersion" json:"stream_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStartNotification) Reset() {
	*x = StreamStartNotification{}
	mi := &file_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStartNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStartNotification) ProtoMessage() {}

func (x *StreamStartNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStartNotification.ProtoReflect.Descriptor instead.
func (*StreamStartNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *StreamStartNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *StreamStartNotification) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *StreamStartNotification) GetStreamVersion() StreamVersion {
	if x != nil && x.StreamVersion != nil {
		return *x.StreamVersion
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

type StreamEndNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEndNotification) Reset() {
	*x = StreamEndNotification{}
	mi := &file_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEndNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEndNotification) ProtoMessage() {}

func (x *StreamEndNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEndNotification.ProtoReflect.Descriptor instead.
func (*StreamEndNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *StreamEndNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

type HeartbeatNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      *string                `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Draining      *bool                  `protobuf:"varint,2,opt,name=draining" json:"draining,omitempty"`
	JobCount      *uint64                `protobuf:"varint,3,opt,name=job_count,json=jobCount" json:"job_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatNotification) Reset() {
	*x = HeartbeatNotification{}
	mi := &file_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNotification) ProtoMessage() {}

func (x *HeartbeatNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNotification.ProtoReflect.Descriptor instead.
func (*HeartbeatNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatNotification) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *HeartbeatNotification) GetDraining() bool {
	if x != nil && x.Draining != nil {
		return *x.Draining
	}
	return false
}

func (x *HeartbeatNotification) GetJobCount() uint64 {
	if x != nil && x.JobCount != nil {
		return *x.JobCount
	}
	return 0
}

type VODReadyNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	StreamVersion *StreamVersion         `protobuf:"varint,2,opt,name=stream_version,json=streamVersion,enum=protobuf.StreamVersion" json:"stream_version,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VODReadyNotification) Reset() {
	*x = VODReadyNotification{}
	mi := &file_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VODReadyNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VODReadyNotification) ProtoMessage() {}

func (x *VODReadyNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VODReadyNotification.ProtoReflect.Descriptor instead.
func (*VODReadyNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *VODReadyNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *VODReadyNotification) GetStreamVersion() StreamVersion {
	if x != nil && x.StreamVersion != nil {
		return *x.StreamVersion
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

func (x *VODReadyNotification) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type ThumbnailReadyNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	StreamVersion *StreamVersion         `protobuf:"varint,2,opt,name=stream_version,json=streamVersion,enum=protobuf.StreamVersion" json:"stream_version,omitempty"`
	Thumbnail     []byte                 `protobuf:"bytes,3,opt,name=thumbnail" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailReadyNotification) Reset() {
	*x = ThumbnailReadyNotification{}
	mi := &file_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailReadyNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailReadyNotification) ProtoMessage() {}

func (x *ThumbnailReadyNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailReadyNotification.ProtoReflect.Descriptor instead.
func (*ThumbnailReadyNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *ThumbnailReadyNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *ThumbnailReadyNotification) GetStreamVersion() StreamVersion {
	if x != nil && x.StreamVersion != nil {
		return *x.StreamVersion
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

func (x *ThumbnailReadyNotification) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

// JobUpdateNotification is sent when a job's status changes
type JobUpdateNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	RunnerHostname *string                `protobuf:"bytes,2,opt,name=runner_hostname,json=runnerHostname" json:"runner_hostname,omitempty"`
	Stream         *StreamInfo            `protobuf:"bytes,3,opt,name=stream" json:"stream,omitempty"`
	StreamVersion  *StreamVersion         `protobuf:"varint,4,opt,name=stream_version,json=streamVersion,enum=protobuf.StreamVersion" json:"stream_version,omitempty"`
	Status         *JobStatus             `protobuf:"varint,5,opt,name=status,enum=protobuf.JobStatus" json:"status,omitempty"`
	CurrentAction  *ActionType            `protobuf:"varint,6,opt,name=current_action,json=currentAction,enum=protobuf.ActionType" json:"current_action,omitempty"`
	Progress       *uint32                `protobuf:"varint,7,opt,name=progress" json:"progress,omitempty"`
	ErrorMessage   *string                `protobuf:"bytes,8,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobUpdateNotification) Reset() {
	*x = JobUpdateNotification{}
	mi := &file_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdateNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdateNotification) ProtoMessage() {}

func (x *JobUpdateNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdateNotification.ProtoReflect.Descriptor instead.
func (*JobUpdateNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *JobUpdateNotification) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *JobUpdateNotification) GetRunnerHostname() string {
	if x != nil && x.RunnerHostname != nil {
		return *x.RunnerHostname
	}
	return ""
}

func (x *JobUpdateNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *JobUpdateNotification) GetStreamVersion() StreamVersion {
	if x != nil && x.StreamVersion != nil {
		return *x.StreamVersion
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

func (x *JobUpdateNotification) GetStatus() JobStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobUpdateNotification) GetCurrentAction() ActionType {
	if x != nil && x.CurrentAction != nil {
		return *x.CurrentAction
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *JobUpdateNotification) GetProgress() uint32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *JobUpdateNotification) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{8}
}

var File_notifications_proto protoreflect.FileDescriptor

const file_notifications_proto_rawDesc = "" +
	"\n" +
	"\x13notifications.proto\x12\bprotobuf\x1a\rcommons.proto\"\xb3\x03\n" +
	"\fNotification\x12F\n" +
	"\fstream_start\x18\x01 \x01(\v2!.protobuf.StreamStartNotificationH\x00R\vstreamStart\x12@\n" +
	"\n" +
	"stream_end\x18\x02 \x01(\v2\x1f.protobuf.StreamEndNotificationH\x00R\tstreamEnd\x12?\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1f.protobuf.HeartbeatNotificationH\x00R\theartbeat\x12=\n" +
	"\tvod_ready\x18\x04 \x01(\v2\x1e.protobuf.VODReadyNotificationH\x00R\bvodReady\x12O\n" +
	"\x0fthumbnail_ready\x18\x05 \x01(\v2$.protobuf.ThumbnailReadyNotificationH\x00R\x0ethumbnailReady\x12@\n" +
	"\n" +
	"job_update\x18\x06 \x01(\v2\x1f.protobuf.JobUpdateNotificationH\x00R\tjobUpdateB\x06\n" +
	"\x04data\"\x1c\n" +
	"\n" +
	"StreamInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x99\x01\n" +
	"\x17StreamStartNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12>\n" +
	"\x0estream_version\x18\x03 \x01(\x0e2\x17.protobuf.StreamVersionR\rstreamVersion\"E\n" +
	"\x15StreamEndNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\"l\n" +
	"\x15HeartbeatNotification\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bdraining\x18\x02 \x01(\bR\bdraining\x12\x1b\n" +
	"\tjob_count\x18\x03 \x01(\x04R\bjobCount\"\x96\x01\n" +
	"\x14VODReadyNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\x12>\n" +
	"\x0estream_version\x18\x02 \x01(\x0e2\x17.protobuf.StreamVersionR\rstreamVersion\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xa8\x01\n" +
	"\x1aThumbnailReadyNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\x12>\n" +
	"\x0estream_version\x18\x02 \x01(\x0e2\x17.protobuf.StreamVersionR\rstreamVersion\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\fR\tthumbnail\"\xf0\x02\n" +
	"\x15JobUpdateNotification\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12'\n" +
	"\x0frunner_hostname\x18\x02 \x01(\tR\x0erunnerHostname\x12,\n" +
	"\x06stream\x18\x03 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\x12>\n" +
	"\x0estream_version\x18\x04 \x01(\x0e2\x17.protobuf.StreamVersionR\rstreamVersion\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.protobuf.JobStatusR\x06status\x12;\n" +
	"\x0ecurrent_action\x18\x06 \x01(\x0e2\x14.protobuf.ActionTypeR\rcurrentAction\x12\x1a\n" +
	"\bprogress\x18\a \x01(\rR\bprogress\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\x16\n" +
	"\x14NotificationResponse*\xa2\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_CREATED\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x05*\xaa\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACTION_TYPE_STREAM\x10\x01\x12\x1a\n" +
	"\x16ACTION_TYPE_STREAM_END\x10\x02\x12\x16\n" +
	"\x12ACTION_TYPE_MK_VOD\x10\x03\x12\x19\n" +
	"\x15ACTION_TYPE_CHECK_VOD\x10\x04\x12\x18\n" +
	"\x14ACTION_TYPE_MK_THUMB\x10\x05B\x11Z\x0frunner/protobufb\beditionsp\xe8\a"

var (
	file_notifications_proto_rawDescOnce sync.Once
	file_notifications_proto_rawDescData []byte
)

func file_notifications_proto_rawDescGZIP() []byte {
	file_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)))
	})
	return file_notifications_proto_rawDescData
}

var file_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_notifications_proto_goTypes = []any{
	(JobStatus)(0),                     // 0: protobuf.JobStatus
	(ActionType)(0),                    // 1: protobuf.ActionType
	(*Notification)(nil),               // 2: protobuf.Notification
	(*StreamInfo)(nil),                 // 3: protobuf.StreamInfo
	(*StreamStartNotification)(nil),    // 4: protobuf.StreamStartNotification
	(*StreamEndNotification)(nil),      // 5: protobuf.StreamEndNotification
	(*HeartbeatNotification)(nil),      // 6: protobuf.HeartbeatNotification
	(*VODReadyNotification)(nil),       // 7: protobuf.VODReadyNotification
	(*ThumbnailReadyNotification)(nil), // 8: protobuf.ThumbnailReadyNotification
	(*JobUpdateNotification)(nil),      // 9: protobuf.JobUpdateNotification
	(*NotificationResponse)(nil),       // 10: protobuf.NotificationResponse
	(StreamVersion)(0),                 // 11: protobuf.StreamVersion
}
var file_notifications_proto_depIdxs = []int32{
	4,  // 0: protobuf.Notification.stream_start:type_name -> protobuf.StreamStartNotification
	5,  // 1: protobuf.Notification.stream_end:type_name -> protobuf.StreamEndNotification
	6,  // 2: protobuf.Notification.heartbeat:type_name -> protobuf.HeartbeatNotification
	7,  // 3: protobuf.Notification.vod_ready:type_name -> protobuf.VODReadyNotification
	8,  // 4: protobuf.Notification.thumbnail_ready:type_name -> protobuf.ThumbnailReadyNotification
	9,  // 5: protobuf.Notification.job_update:type_name -> protobuf.JobUpdateNotification
	3,  // 6: protobuf.StreamStartNotification.stream:type_name -> protobuf.StreamInfo
	11, // 7: protobuf.StreamStartNotification.stream_version:type_name -> protobuf.StreamVersion
	3,  // 8: protobuf.StreamEndNotification.stream:type_name -> protobuf.StreamInfo
	3,  // 9: protobuf.VODReadyNotification.stream:type_name -> protobuf.StreamInfo
	11, // 10: protobuf.VODReadyNotification.stream_version:type_name -> protobuf.StreamVersion
	3,  // 11: protobuf.ThumbnailReadyNotification.stream:type_name -> protobuf.StreamInfo
	11, // 12: protobuf.ThumbnailReadyNotification.stream_version:type_name -> protobuf.StreamVersion
	3,  // 13: protobuf.JobUpdateNotification.stream:type_name -> protobuf.StreamInfo
	11, // 14: protobuf.JobUpdateNotification.stream_version:type_name -> protobuf.StreamVersion
	0,  // 15: protobuf.JobUpdateNotification.status:type_name -> protobuf.JobStatus
	1,  // 16: protobuf.JobUpdateNotification.current_action:type_name -> protobuf.ActionType
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_notifications_proto_init() }
func file_notifications_proto_init() {
	if File_notifications_proto != nil {
		return
	}
	file_commons_proto_init()
	file_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*Notification_StreamStart)(nil),
		(*Notification_StreamEnd)(nil),
		(*Notification_Heartbeat)(nil),
		(*Notification_VodReady)(nil),
		(*Notification_ThumbnailReady)(nil),
		(*Notification_JobUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_proto_depIdxs,
		EnumInfos:         file_notifications_proto_enumTypes,
		MessageInfos:      file_notifications_proto_msgTypes,
	}.Build()
	File_notifications_proto = out.File
	file_notifications_proto_goTypes = nil
	file_notifications_proto_depIdxs = nil
}
