// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: notifications.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Notification_StreamStart
	//	*Notification_StreamEnd
	//	*Notification_Heartbeat
	//	*Notification_VodReady
	//	*Notification_ThumbnailReady
	Data          isNotification_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetData() isNotification_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetStreamStart() *StreamStartNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_StreamStart); ok {
			return x.StreamStart
		}
	}
	return nil
}

func (x *Notification) GetStreamEnd() *StreamEndNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_StreamEnd); ok {
			return x.StreamEnd
		}
	}
	return nil
}

func (x *Notification) GetHeartbeat() *HeartbeatNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Notification) GetVodReady() *VODReadyNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_VodReady); ok {
			return x.VodReady
		}
	}
	return nil
}

func (x *Notification) GetThumbnailReady() *ThumbnailReadyNotification {
	if x != nil {
		if x, ok := x.Data.(*Notification_ThumbnailReady); ok {
			return x.ThumbnailReady
		}
	}
	return nil
}

type isNotification_Data interface {
	isNotification_Data()
}

type Notification_StreamStart struct {
	StreamStart *StreamStartNotification `protobuf:"bytes,1,opt,name=stream_start,json=streamStart,oneof"`
}

type Notification_StreamEnd struct {
	StreamEnd *StreamEndNotification `protobuf:"bytes,2,opt,name=stream_end,json=streamEnd,oneof"`
}

type Notification_Heartbeat struct {
	Heartbeat *HeartbeatNotification `protobuf:"bytes,3,opt,name=heartbeat,oneof"`
}

type Notification_VodReady struct {
	VodReady *VODReadyNotification `protobuf:"bytes,4,opt,name=vod_ready,json=vodReady,oneof"`
}

type Notification_ThumbnailReady struct {
	ThumbnailReady *ThumbnailReadyNotification `protobuf:"bytes,5,opt,name=thumbnail_ready,json=thumbnailReady,oneof"`
}

func (*Notification_StreamStart) isNotification_Data() {}

func (*Notification_StreamEnd) isNotification_Data() {}

func (*Notification_Heartbeat) isNotification_Data() {}

func (*Notification_VodReady) isNotification_Data() {}

func (*Notification_ThumbnailReady) isNotification_Data() {}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *StreamInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type StreamStartNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	Url           *string                `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	StreamVersion *StreamVersion         `protobuf:"varint,3,opt,name=stream_version,json=streamVersion,enum=protobuf.StreamVersion" json:"stream_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStartNotification) Reset() {
	*x = StreamStartNotification{}
	mi := &file_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStartNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStartNotification) ProtoMessage() {}

func (x *StreamStartNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStartNotification.ProtoReflect.Descriptor instead.
func (*StreamStartNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *StreamStartNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *StreamStartNotification) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *StreamStartNotification) GetStreamVersion() StreamVersion {
	if x != nil && x.StreamVersion != nil {
		return *x.StreamVersion
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

type StreamEndNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEndNotification) Reset() {
	*x = StreamEndNotification{}
	mi := &file_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEndNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEndNotification) ProtoMessage() {}

func (x *StreamEndNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEndNotification.ProtoReflect.Descriptor instead.
func (*StreamEndNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *StreamEndNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

type HeartbeatNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      *string                `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Draining      *bool                  `protobuf:"varint,2,opt,name=draining" json:"draining,omitempty"`
	JobCount      *uint64                `protobuf:"varint,3,opt,name=job_count,json=jobCount" json:"job_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatNotification) Reset() {
	*x = HeartbeatNotification{}
	mi := &file_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNotification) ProtoMessage() {}

func (x *HeartbeatNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNotification.ProtoReflect.Descriptor instead.
func (*HeartbeatNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatNotification) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *HeartbeatNotification) GetDraining() bool {
	if x != nil && x.Draining != nil {
		return *x.Draining
	}
	return false
}

func (x *HeartbeatNotification) GetJobCount() uint64 {
	if x != nil && x.JobCount != nil {
		return *x.JobCount
	}
	return 0
}

type VODReadyNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	StreamVersion *StreamVersion         `protobuf:"varint,2,opt,name=stream_version,json=streamVersion,enum=protobuf.StreamVersion" json:"stream_version,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VODReadyNotification) Reset() {
	*x = VODReadyNotification{}
	mi := &file_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VODReadyNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VODReadyNotification) ProtoMessage() {}

func (x *VODReadyNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VODReadyNotification.ProtoReflect.Descriptor instead.
func (*VODReadyNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *VODReadyNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *VODReadyNotification) GetStreamVersion() StreamVersion {
	if x != nil && x.StreamVersion != nil {
		return *x.StreamVersion
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

func (x *VODReadyNotification) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type ThumbnailReadyNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *StreamInfo            `protobuf:"bytes,1,opt,name=stream" json:"stream,omitempty"`
	StreamVersion *StreamVersion         `protobuf:"varint,2,opt,name=stream_version,json=streamVersion,enum=protobuf.StreamVersion" json:"stream_version,omitempty"`
	Thumbnail     []byte                 `protobuf:"bytes,3,opt,name=thumbnail" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailReadyNotification) Reset() {
	*x = ThumbnailReadyNotification{}
	mi := &file_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailReadyNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailReadyNotification) ProtoMessage() {}

func (x *ThumbnailReadyNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailReadyNotification.ProtoReflect.Descriptor instead.
func (*ThumbnailReadyNotification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *ThumbnailReadyNotification) GetStream() *StreamInfo {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *ThumbnailReadyNotification) GetStreamVersion() StreamVersion {
	if x != nil && x.StreamVersion != nil {
		return *x.StreamVersion
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

func (x *ThumbnailReadyNotification) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{7}
}

var File_notifications_proto protoreflect.FileDescriptor

const file_notifications_proto_rawDesc = "" +
	"\n" +
	"\x13notifications.proto\x12\bprotobuf\x1a\rcommons.proto\"\xf1\x02\n" +
	"\fNotification\x12F\n" +
	"\fstream_start\x18\x01 \x01(\v2!.protobuf.StreamStartNotificationH\x00R\vstreamStart\x12@\n" +
	"\n" +
	"stream_end\x18\x02 \x01(\v2\x1f.protobuf.StreamEndNotificationH\x00R\tstreamEnd\x12?\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1f.protobuf.HeartbeatNotificationH\x00R\theartbeat\x12=\n" +
	"\tvod_ready\x18\x04 \x01(\v2\x1e.protobuf.VODReadyNotificationH\x00R\bvodReady\x12O\n" +
	"\x0fthumbnail_ready\x18\x05 \x01(\v2$.protobuf.ThumbnailReadyNotificationH\x00R\x0ethumbnailReadyB\x06\n" +
	"\x04data\"\x1c\n" +
	"\n" +
	"StreamInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x99\x01\n" +
	"\x17StreamStartNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12>\n" +
	"\x0estream_version\x18\x03 \x01(\x0e2\x17.protobuf.StreamVersionR\rstreamVersion\"E\n" +
	"\x15StreamEndNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\"l\n" +
	"\x15HeartbeatNotification\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bdraining\x18\x02 \x01(\bR\bdraining\x12\x1b\n" +
	"\tjob_count\x18\x03 \x01(\x04R\bjobCount\"\x96\x01\n" +
	"\x14VODReadyNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\x12>\n" +
	"\x0estream_version\x18\x02 \x01(\x0e2\x17.protobuf.StreamVersionR\rstreamVersion\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xa8\x01\n" +
	"\x1aThumbnailReadyNotification\x12,\n" +
	"\x06stream\x18\x01 \x01(\v2\x14.protobuf.StreamInfoR\x06stream\x12>\n" +
	"\x0estream_version\x18\x02 \x01(\x0e2\x17.protobuf.StreamVersionR\rstreamVersion\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\fR\tthumbnail\"\x16\n" +
	"\x14NotificationResponseB\x11Z\x0frunner/protobufb\beditionsp\xe8\a"

var (
	file_notifications_proto_rawDescOnce sync.Once
	file_notifications_proto_rawDescData []byte
)

func file_notifications_proto_rawDescGZIP() []byte {
	file_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)))
	})
	return file_notifications_proto_rawDescData
}

var file_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notifications_proto_goTypes = []any{
	(*Notification)(nil),               // 0: protobuf.Notification
	(*StreamInfo)(nil),                 // 1: protobuf.StreamInfo
	(*StreamStartNotification)(nil),    // 2: protobuf.StreamStartNotification
	(*StreamEndNotification)(nil),      // 3: protobuf.StreamEndNotification
	(*HeartbeatNotification)(nil),      // 4: protobuf.HeartbeatNotification
	(*VODReadyNotification)(nil),       // 5: protobuf.VODReadyNotification
	(*ThumbnailReadyNotification)(nil), // 6: protobuf.ThumbnailReadyNotification
	(*NotificationResponse)(nil),       // 7: protobuf.NotificationResponse
	(StreamVersion)(0),                 // 8: protobuf.StreamVersion
}
var file_notifications_proto_depIdxs = []int32{
	2,  // 0: protobuf.Notification.stream_start:type_name -> protobuf.StreamStartNotification
	3,  // 1: protobuf.Notification.stream_end:type_name -> protobuf.StreamEndNotification
	4,  // 2: protobuf.Notification.heartbeat:type_name -> protobuf.HeartbeatNotification
	5,  // 3: protobuf.Notification.vod_ready:type_name -> protobuf.VODReadyNotification
	6,  // 4: protobuf.Notification.thumbnail_ready:type_name -> protobuf.ThumbnailReadyNotification
	1,  // 5: protobuf.StreamStartNotification.stream:type_name -> protobuf.StreamInfo
	8,  // 6: protobuf.StreamStartNotification.stream_version:type_name -> protobuf.StreamVersion
	1,  // 7: protobuf.StreamEndNotification.stream:type_name -> protobuf.StreamInfo
	1,  // 8: protobuf.VODReadyNotification.stream:type_name -> protobuf.StreamInfo
	8,  // 9: protobuf.VODReadyNotification.stream_version:type_name -> protobuf.StreamVersion
	1,  // 10: protobuf.ThumbnailReadyNotification.stream:type_name -> protobuf.StreamInfo
	8,  // 11: protobuf.ThumbnailReadyNotification.stream_version:type_name -> protobuf.StreamVersion
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_notifications_proto_init() }
func file_notifications_proto_init() {
	if File_notifications_proto != nil {
		return
	}
	file_commons_proto_init()
	file_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*Notification_StreamStart)(nil),
		(*Notification_StreamEnd)(nil),
		(*Notification_Heartbeat)(nil),
		(*Notification_VodReady)(nil),
		(*Notification_ThumbnailReady)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_proto_depIdxs,
		MessageInfos:      file_notifications_proto_msgTypes,
	}.Build()
	File_notifications_proto = out.File
	file_notifications_proto_goTypes = nil
	file_notifications_proto_depIdxs = nil
}
