// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: runner.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StreamId            *uint64                `protobuf:"varint,1,opt,name=stream_id,json=streamId" json:"stream_id,omitempty"`
	Version             *StreamVersion         `protobuf:"varint,2,opt,name=version,enum=protobuf.StreamVersion" json:"version,omitempty"`
	End                 *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end" json:"end,omitempty"`
	FfmpegGlobalOptions *string                `protobuf:"bytes,4,opt,name=ffmpeg_global_options,json=ffmpegGlobalOptions" json:"ffmpeg_global_options,omitempty"` // optional e.g. -rtsp_transport tcp
	FfmpegInputOptions  *string                `protobuf:"bytes,5,opt,name=ffmpeg_input_options,json=ffmpegInputOptions" json:"ffmpeg_input_options,omitempty"`    // optional
	FfmpegOutputOptions *string                `protobuf:"bytes,6,opt,name=ffmpeg_output_options,json=ffmpegOutputOptions" json:"ffmpeg_output_options,omitempty"` // e.g. -c:a copy -c:v copy
	Input               *string                `protobuf:"bytes,7,opt,name=input" json:"input,omitempty"`                                                          // e.g. rtsp://user:password@host:port/rtsp_path
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetStreamId() uint64 {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return 0
}

func (x *StreamRequest) GetVersion() StreamVersion {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

func (x *StreamRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *StreamRequest) GetFfmpegGlobalOptions() string {
	if x != nil && x.FfmpegGlobalOptions != nil {
		return *x.FfmpegGlobalOptions
	}
	return ""
}

func (x *StreamRequest) GetFfmpegInputOptions() string {
	if x != nil && x.FfmpegInputOptions != nil {
		return *x.FfmpegInputOptions
	}
	return ""
}

func (x *StreamRequest) GetFfmpegOutputOptions() string {
	if x != nil && x.FfmpegOutputOptions != nil {
		return *x.FfmpegOutputOptions
	}
	return ""
}

func (x *StreamRequest) GetInput() string {
	if x != nil && x.Input != nil {
		return *x.Input
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

type StreamEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	DiscardVod    *bool                  `protobuf:"varint,2,opt,name=discard_vod,json=discardVod" json:"discard_vod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEndRequest) Reset() {
	*x = StreamEndRequest{}
	mi := &file_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEndRequest) ProtoMessage() {}

func (x *StreamEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEndRequest.ProtoReflect.Descriptor instead.
func (*StreamEndRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2}
}

func (x *StreamEndRequest) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *StreamEndRequest) GetDiscardVod() bool {
	if x != nil && x.DiscardVod != nil {
		return *x.DiscardVod
	}
	return false
}

type StreamEndResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEndResponse) Reset() {
	*x = StreamEndResponse{}
	mi := &file_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEndResponse) ProtoMessage() {}

func (x *StreamEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEndResponse.ProtoReflect.Descriptor instead.
func (*StreamEndResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3}
}

// SectionTimestamp is the offset into a recording at which a section starts.
type SectionTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     *uint64                `protobuf:"varint,1,opt,name=section_id,json=sectionId" json:"section_id,omitempty"`
	Hours         *uint32                `protobuf:"varint,2,opt,name=hours" json:"hours,omitempty"`
	Minutes       *uint32                `protobuf:"varint,3,opt,name=minutes" json:"minutes,omitempty"`
	Seconds       *uint32                `protobuf:"varint,4,opt,name=seconds" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionTimestamp) Reset() {
	*x = SectionTimestamp{}
	mi := &file_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionTimestamp) ProtoMessage() {}

func (x *SectionTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionTimestamp.ProtoReflect.Descriptor instead.
func (*SectionTimestamp) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{4}
}

func (x *SectionTimestamp) GetSectionId() uint64 {
	if x != nil && x.SectionId != nil {
		return *x.SectionId
	}
	return 0
}

func (x *SectionTimestamp) GetHours() uint32 {
	if x != nil && x.Hours != nil {
		return *x.Hours
	}
	return 0
}

func (x *SectionTimestamp) GetMinutes() uint32 {
	if x != nil && x.Minutes != nil {
		return *x.Minutes
	}
	return 0
}

func (x *SectionTimestamp) GetSeconds() uint32 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

type SectionImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      *uint64                `protobuf:"varint,1,opt,name=stream_id,json=streamId" json:"stream_id,omitempty"`
	PlaylistUrl   *string                `protobuf:"bytes,2,opt,name=playlist_url,json=playlistUrl" json:"playlist_url,omitempty"`
	Sections      []*SectionTimestamp    `protobuf:"bytes,3,rep,name=sections" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionImageRequest) Reset() {
	*x = SectionImageRequest{}
	mi := &file_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionImageRequest) ProtoMessage() {}

func (x *SectionImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionImageRequest.ProtoReflect.Descriptor instead.
func (*SectionImageRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{5}
}

func (x *SectionImageRequest) GetStreamId() uint64 {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return 0
}

func (x *SectionImageRequest) GetPlaylistUrl() string {
	if x != nil && x.PlaylistUrl != nil {
		return *x.PlaylistUrl
	}
	return ""
}

func (x *SectionImageRequest) GetSections() []*SectionTimestamp {
	if x != nil {
		return x.Sections
	}
	return nil
}

type SectionImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionImageResponse) Reset() {
	*x = SectionImageResponse{}
	mi := &file_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionImageResponse) ProtoMessage() {}

func (x *SectionImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionImageResponse.ProtoReflect.Descriptor instead.
func (*SectionImageResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{6}
}

func (x *SectionImageResponse) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      *string                `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Port          *int32                 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Version       *string                `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{8}
}

var File_runner_proto protoreflect.FileDescriptor

const file_runner_proto_rawDesc = "" +
	"\n" +
	"\frunner.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rcommons.proto\x1a\x13notifications.proto\"\xbd\x02\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x121\n" +
	"\aversion\x18\x02 \x01(\x0e2\x17.protobuf.StreamVersionR\aversion\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x122\n" +
	"\x15ffmpeg_global_options\x18\x04 \x01(\tR\x13ffmpegGlobalOptions\x120\n" +
	"\x14ffmpeg_input_options\x18\x05 \x01(\tR\x12ffmpegInputOptions\x122\n" +
	"\x15ffmpeg_output_options\x18\x06 \x01(\tR\x13ffmpegOutputOptions\x12\x14\n" +
	"\x05input\x18\a \x01(\tR\x05input\"'\n" +
	"\x0eStreamResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"J\n" +
	"\x10StreamEndRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vdiscard_vod\x18\x02 \x01(\bR\n" +
	"discardVod\"\x13\n" +
	"\x11StreamEndResponse\"{\n" +
	"\x10SectionTimestamp\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x04R\tsectionId\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\rR\x05hours\x12\x18\n" +
	"\aminutes\x18\x03 \x01(\rR\aminutes\x12\x18\n" +
	"\aseconds\x18\x04 \x01(\rR\aseconds\"\x8d\x01\n" +
	"\x13SectionImageRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x12!\n" +
	"\fplaylist_url\x18\x02 \x01(\tR\vplaylistUrl\x126\n" +
	"\bsections\x18\x03 \x03(\v2\x1a.protobuf.SectionTimestampR\bsections\"-\n" +
	"\x14SectionImageResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"[\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x12\n" +
	"\x10RegisterResponse2\xfd\x01\n" +
	"\rRunnerService\x12D\n" +
	"\rRequestStream\x12\x17.protobuf.StreamRequest\x1a\x18.protobuf.StreamResponse\"\x00\x12M\n" +
	"\x10RequestStreamEnd\x12\x1a.protobuf.StreamEndRequest\x1a\x1b.protobuf.StreamEndResponse\"\x00\x12W\n" +
	"\x14RequestSectionImages\x12\x1d.protobuf.SectionImageRequest\x1a\x1e.protobuf.SectionImageResponse\"\x002\x9f\x01\n" +
	"\x14RunnerManagerService\x12C\n" +
	"\bRegister\x12\x19.protobuf.RegisterRequest\x1a\x1a.protobuf.RegisterResponse\"\x00\x12B\n" +
	"\x06Notify\x12\x16.protobuf.Notification\x1a\x1e.protobuf.NotificationResponse\"\x00B\x11Z\x0frunner/protobufb\beditionsp\xe8\a"

var (
	file_runner_proto_rawDescOnce sync.Once
	file_runner_proto_rawDescData []byte
)

func file_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)))
	})
	return file_runner_proto_rawDescData
}

var file_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_runner_proto_goTypes = []any{
	(*StreamRequest)(nil),         // 0: protobuf.StreamRequest
	(*StreamResponse)(nil),        // 1: protobuf.StreamResponse
	(*StreamEndRequest)(nil),      // 2: protobuf.StreamEndRequest
	(*StreamEndResponse)(nil),     // 3: protobuf.StreamEndResponse
	(*SectionTimestamp)(nil),      // 4: protobuf.SectionTimestamp
	(*SectionImageRequest)(nil),   // 5: protobuf.SectionImageRequest
	(*SectionImageResponse)(nil),  // 6: protobuf.SectionImageResponse
	(*RegisterRequest)(nil),       // 7: protobuf.RegisterRequest
	(*RegisterResponse)(nil),      // 8: protobuf.RegisterResponse
	(StreamVersion)(0),            // 9: protobuf.StreamVersion
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*Notification)(nil),          // 11: protobuf.Notification
	(*NotificationResponse)(nil),  // 12: protobuf.NotificationResponse
}
var file_runner_proto_depIdxs = []int32{
	9,  // 0: protobuf.StreamRequest.version:type_name -> protobuf.StreamVersion
	10, // 1: protobuf.StreamRequest.end:type_name -> google.protobuf.Timestamp
	4,  // 2: protobuf.SectionImageRequest.sections:type_name -> protobuf.SectionTimestamp
	0,  // 3: protobuf.RunnerService.RequestStream:input_type -> protobuf.StreamRequest
	2,  // 4: protobuf.RunnerService.RequestStreamEnd:input_type -> protobuf.StreamEndRequest
	5,  // 5: protobuf.RunnerService.RequestSectionImages:input_type -> protobuf.SectionImageRequest
	7,  // 6: protobuf.RunnerManagerService.Register:input_type -> protobuf.RegisterRequest
	11, // 7: protobuf.RunnerManagerService.Notify:input_type -> protobuf.Notification
	1,  // 8: protobuf.RunnerService.RequestStream:output_type -> protobuf.StreamResponse
	3,  // 9: protobuf.RunnerService.RequestStreamEnd:output_type -> protobuf.StreamEndResponse
	6,  // 10: protobuf.RunnerService.RequestSectionImages:output_type -> protobuf.SectionImageResponse
	8,  // 11: protobuf.RunnerManagerService.Register:output_type -> protobuf.RegisterResponse
	12, // 12: protobuf.RunnerManagerService.Notify:output_type -> protobuf.NotificationResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_runner_proto_init() }
func file_runner_proto_init() {
	if File_runner_proto != nil {
		return
	}
	file_commons_proto_init()
	file_notifications_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_depIdxs,
		MessageInfos:      file_runner_proto_msgTypes,
	}.Build()
	File_runner_proto = out.File
	file_runner_proto_goTypes = nil
	file_runner_proto_depIdxs = nil
}
