// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: runner.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StreamId            *uint64                `protobuf:"varint,1,opt,name=stream_id,json=streamId" json:"stream_id,omitempty"`
	Version             *StreamVersion         `protobuf:"varint,2,opt,name=version,enum=protobuf.StreamVersion" json:"version,omitempty"`
	End                 *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end" json:"end,omitempty"`
	FfmpegGlobalOptions *string                `protobuf:"bytes,4,opt,name=ffmpeg_global_options,json=ffmpegGlobalOptions" json:"ffmpeg_global_options,omitempty"` // optional e.g. -rtsp_transport tcp
	FfmpegInputOptions  *string                `protobuf:"bytes,5,opt,name=ffmpeg_input_options,json=ffmpegInputOptions" json:"ffmpeg_input_options,omitempty"`    // optional
	FfmpegOutputOptions *string                `protobuf:"bytes,6,opt,name=ffmpeg_output_options,json=ffmpegOutputOptions" json:"ffmpeg_output_options,omitempty"` // e.g. -c:a copy -c:v copy
	Input               *string                `protobuf:"bytes,7,opt,name=input" json:"input,omitempty"`                                                          // e.g. rtsp://user:password@host:port/rtsp_path
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetStreamId() uint64 {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return 0
}

func (x *StreamRequest) GetVersion() StreamVersion {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return StreamVersion_STREAM_VERSION_UNSPECIFIED
}

func (x *StreamRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *StreamRequest) GetFfmpegGlobalOptions() string {
	if x != nil && x.FfmpegGlobalOptions != nil {
		return *x.FfmpegGlobalOptions
	}
	return ""
}

func (x *StreamRequest) GetFfmpegInputOptions() string {
	if x != nil && x.FfmpegInputOptions != nil {
		return *x.FfmpegInputOptions
	}
	return ""
}

func (x *StreamRequest) GetFfmpegOutputOptions() string {
	if x != nil && x.FfmpegOutputOptions != nil {
		return *x.FfmpegOutputOptions
	}
	return ""
}

func (x *StreamRequest) GetInput() string {
	if x != nil && x.Input != nil {
		return *x.Input
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

type StreamEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         *string                `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEndRequest) Reset() {
	*x = StreamEndRequest{}
	mi := &file_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEndRequest) ProtoMessage() {}

func (x *StreamEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEndRequest.ProtoReflect.Descriptor instead.
func (*StreamEndRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2}
}

func (x *StreamEndRequest) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

type StreamEndResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEndResponse) Reset() {
	*x = StreamEndResponse{}
	mi := &file_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEndResponse) ProtoMessage() {}

func (x *StreamEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEndResponse.ProtoReflect.Descriptor instead.
func (*StreamEndResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      *string                `protobuf:"bytes,1,opt,name=hostname" json:"hostname,omitempty"`
	Port          *int32                 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Version       *string                `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{5}
}

var File_runner_proto protoreflect.FileDescriptor

const file_runner_proto_rawDesc = "" +
	"\n" +
	"\frunner.proto\x12\bprotobuf\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rcommons.proto\x1a\x13notifications.proto\"\xbd\x02\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\x04R\bstreamId\x121\n" +
	"\aversion\x18\x02 \x01(\x0e2\x17.protobuf.StreamVersionR\aversion\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x122\n" +
	"\x15ffmpeg_global_options\x18\x04 \x01(\tR\x13ffmpegGlobalOptions\x120\n" +
	"\x14ffmpeg_input_options\x18\x05 \x01(\tR\x12ffmpegInputOptions\x122\n" +
	"\x15ffmpeg_output_options\x18\x06 \x01(\tR\x13ffmpegOutputOptions\x12\x14\n" +
	"\x05input\x18\a \x01(\tR\x05input\"'\n" +
	"\x0eStreamResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\")\n" +
	"\x10StreamEndRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x13\n" +
	"\x11StreamEndResponse\"[\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x12\n" +
	"\x10RegisterResponse2\xa4\x01\n" +
	"\rRunnerService\x12D\n" +
	"\rRequestStream\x12\x17.protobuf.StreamRequest\x1a\x18.protobuf.StreamResponse\"\x00\x12M\n" +
	"\x10RequestStreamEnd\x12\x1a.protobuf.StreamEndRequest\x1a\x1b.protobuf.StreamEndResponse\"\x002\x9f\x01\n" +
	"\x14RunnerManagerService\x12C\n" +
	"\bRegister\x12\x19.protobuf.RegisterRequest\x1a\x1a.protobuf.RegisterResponse\"\x00\x12B\n" +
	"\x06Notify\x12\x16.protobuf.Notification\x1a\x1e.protobuf.NotificationResponse\"\x00B\x11Z\x0frunner/protobufb\beditionsp\xe8\a"

var (
	file_runner_proto_rawDescOnce sync.Once
	file_runner_proto_rawDescData []byte
)

func file_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)))
	})
	return file_runner_proto_rawDescData
}

var file_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_runner_proto_goTypes = []any{
	(*StreamRequest)(nil),         // 0: protobuf.StreamRequest
	(*StreamResponse)(nil),        // 1: protobuf.StreamResponse
	(*StreamEndRequest)(nil),      // 2: protobuf.StreamEndRequest
	(*StreamEndResponse)(nil),     // 3: protobuf.StreamEndResponse
	(*RegisterRequest)(nil),       // 4: protobuf.RegisterRequest
	(*RegisterResponse)(nil),      // 5: protobuf.RegisterResponse
	(StreamVersion)(0),            // 6: protobuf.StreamVersion
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*Notification)(nil),          // 8: protobuf.Notification
	(*NotificationResponse)(nil),  // 9: protobuf.NotificationResponse
}
var file_runner_proto_depIdxs = []int32{
	6, // 0: protobuf.StreamRequest.version:type_name -> protobuf.StreamVersion
	7, // 1: protobuf.StreamRequest.end:type_name -> google.protobuf.Timestamp
	0, // 2: protobuf.RunnerService.RequestStream:input_type -> protobuf.StreamRequest
	2, // 3: protobuf.RunnerService.RequestStreamEnd:input_type -> protobuf.StreamEndRequest
	4, // 4: protobuf.RunnerManagerService.Register:input_type -> protobuf.RegisterRequest
	8, // 5: protobuf.RunnerManagerService.Notify:input_type -> protobuf.Notification
	1, // 6: protobuf.RunnerService.RequestStream:output_type -> protobuf.StreamResponse
	3, // 7: protobuf.RunnerService.RequestStreamEnd:output_type -> protobuf.StreamEndResponse
	5, // 8: protobuf.RunnerManagerService.Register:output_type -> protobuf.RegisterResponse
	9, // 9: protobuf.RunnerManagerService.Notify:output_type -> protobuf.NotificationResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_runner_proto_init() }
func file_runner_proto_init() {
	if File_runner_proto != nil {
		return
	}
	file_commons_proto_init()
	file_notifications_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_depIdxs,
		MessageInfos:      file_runner_proto_msgTypes,
	}.Build()
	File_runner_proto = out.File
	file_runner_proto_goTypes = nil
	file_runner_proto_depIdxs = nil
}
