name: Build & Deploy

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["worker", "nginx", "edge"]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Docker meta (${{ matrix.module }})
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/joschahenningsen/tum-live/worker-${{ matrix.module }}
          tags: |
            type=sha
          flavor: |
            latest=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push Docker images (${{ matrix.module }})
        uses: docker/build-push-action@v2
        with:
          context: ./worker/${{ matrix.module }}
          pull: true
          push: true
          build-args: version=${{ steps.vars.outputs.sha_short }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
