on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
name: go test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.26.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install modules
        working-directory: ./web
        run: npm ci
      - name: Install Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: go test
        run: go test ./...
