on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
name: go test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.26.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install modules
        working-directory: ./web
        run: npm ci
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: go test
        run: go test ./...
