name: golangci-lint
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./...', './worker', './worker/edge', './runner'] }
    steps:
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.26
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install modules
        working-directory: ./web
        run: npm ci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: latest
          only-new-issues: true

