name: golangci-lint
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./...', './worker', './worker/edge'] }
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: mkdir node_modules
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: true

