name: golangci-lint
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['./...', './worker', './worker/edge', './runner'] }
    steps:
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.26
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install modules
        working-directory: ./web
        run: npm ci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          version: latest
          only-new-issues: true

