name: PR opened

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ dev ]
    types: [ opened ]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Your Testserver will be ready at https://${{ github.event.number }}.test.live.mm.rbg.tum.de in a few minutes.
            <details>
            <summary>Logins</summary>
            
            | Kurs1                                    | Kurs2                     | Kurs3                     | Kurs4                     |
            | ---------------------------------------- | ------------------------- | ------------------------- | ------------------------- |
            | public                                   | public                    | loggedin                  | enrolled                  |
            | prof1                                    | prof1                     | prof2                     | prof1<br/>prof2           |
            | student1<br/>student2<br/>student3       | student1<br/>student2     | student2<br/>student3     | student1<br/>student2     |
            </details>
