name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
  name: "Run CI"
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
      with:
    fetch-depth: 1
      - uses: dominikh/staticcheck-action@v1.1.0
        with:
    version: "2021.1.1"