name: Deploy to Test Server

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'testserver' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: test script
        run: echo Hello, world!

      - name: remove label
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: testserver