name: Deploy to Test Server

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'testserver' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: test script
        run: echo Hello, world!
      - name: 'Ack'
        uses: actions/github-script@0.3.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'I\'ll build a container that will be deployed to the test server in a few minutes!' });
      - name: remove label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: testserver